CREATE SCHEMA IF NOT EXISTS catalogos;

CREATE TABLE CATALOGOS.TC_CATALOGOS
(
  ID           BIGSERIAL                  NOT NULL PRIMARY KEY,
  CLAVE        VARCHAR(10)                NOT NULL,
  DESCRIPCION  VARCHAR(250)               NOT NULL,
  ORIGEN       VARCHAR(100)               NOT NULL,
  RFC_USUARIO  VARCHAR(13)                NOT NULL,
  FECHA        TIMESTAMP(6)               DEFAULT NOW()         NOT NULL
);


CREATE TABLE CATALOGOS.TC_GRADO
(
  CVE_NIVEL    BIGINT                           NOT NULL,
  CVE_GRADO    BIGINT                           NOT NULL,
  GRADO        VARCHAR(20)                NOT NULL,
  RFC_USUARIO  VARCHAR(13)                NOT NULL,
  FECHA        TIMESTAMP(6)                     NOT NULL
);

ALTER TABLE CATALOGOS.TC_GRADO ADD CONSTRAINT TC_GRADO_PK
PRIMARY KEY (CVE_NIVEL, CVE_GRADO);

ALTER TABLE CATALOGOS.TC_GRADO ADD CONSTRAINT TC_GRADO_TC_CATALOGOS_FK1
FOREIGN KEY (CVE_NIVEL)
REFERENCES CATALOGOS.TC_CATALOGOS (ID);


CREATE TABLE CATALOGOS.TC_RAMO
(
  ID_RAMO      BIGSERIAL                        NOT NULL PRIMARY KEY ,
  CLAVE        VARCHAR(10)                NOT NULL,
  DESCRIPCION  VARCHAR(25)
);


ALTER TABLE CATALOGOS.TC_RAMO ADD CONSTRAINT TC_RAMO_UK1
UNIQUE (CLAVE);

CREATE TABLE CATALOGOS.TC_UNIDAD_RESPONSABLE
(
  ID_UNIDAD_RESPONSABLE  BIGSERIAL                 NOT NULL PRIMARY KEY ,
  ID_RAMO                BIGINT                 NOT NULL,
  CLAVE                  VARCHAR(10)      NOT NULL,
  DESCRIPCION            VARCHAR(50),
  CLAVE_UR_CURP          VARCHAR(3),
  CALLE_NUM_SEDE         VARCHAR(250),
  COLONIA_SEDE           VARCHAR(250),
  CP_SEDE                VARCHAR(5),
  CLAVE_PAGADURIA        VARCHAR(5),
  MUNICIPIO_SEDE         VARCHAR(250),
  CVE_ENTIDAD_ORIGEN     VARCHAR(10),
  ID_CENTRO_PAGO_SAR     VARCHAR(10),
  CVE_SERICA             VARCHAR(8)
);


ALTER TABLE CATALOGOS.TC_UNIDAD_RESPONSABLE ADD CONSTRAINT TC_UNIDAD_RESPONSABLE_TC__FK1
FOREIGN KEY (ID_RAMO)
REFERENCES CATALOGOS.TC_RAMO (ID_RAMO);


CREATE TABLE CATALOGOS.TC_ENTIDAD_FEDERATIVA
(
  CVE_ENTIDAD_FEDERATIVA  BIGSERIAL      NOT NULL PRIMARY KEY,
  DESCRIPCION             VARCHAR(50)     NOT NULL,
  RFC_USUARIO             VARCHAR(13)     NOT NULL,
  FECHA                   TIMESTAMP(6)          NOT NULL
);

CREATE TABLE CATALOGOS.TC_MUNICIPIO
(
  CVE_MUNICIPIO           BIGSERIAL      NOT NULL PRIMARY KEY,
  CVE_ENTIDAD_FEDERATIVA  BIGINT     NOT NULL,
  DESCRIPCION             VARCHAR(60)     NOT NULL,
  RFC_USUARIO             VARCHAR(13)     NOT NULL,
  FECHA                   TIMESTAMP(6)          NOT NULL
);

ALTER TABLE CATALOGOS.TC_MUNICIPIO ADD CONSTRAINT TC_MUNICIPIO_TC_ENT_FED_FK1
FOREIGN KEY (CVE_ENTIDAD_FEDERATIVA)
REFERENCES CATALOGOS.TC_ENTIDAD_FEDERATIVA (CVE_ENTIDAD_FEDERATIVA);

CREATE TABLE CATALOGOS.TC_COLONIA
(
  CVE_COLONIA             BIGSERIAL      NOT NULL PRIMARY KEY,
  CVE_ENTIDAD_FEDERATIVA  BIGINT      NOT NULL,
  CVE_MUNICIPIO           BIGINT      NOT NULL,
  DESCRIPCION             VARCHAR(100)    NOT NULL,
  RFC_USUARIO             VARCHAR(13)     NOT NULL,
  FECHA                   TIMESTAMP(6)          NOT NULL,
  CODIGO_POSTAL           VARCHAR(5)      NOT NULL
);

ALTER TABLE CATALOGOS.TC_COLONIA ADD CONSTRAINT TC_COLONIA_TC_MUNICIPIO_FK1
FOREIGN KEY (CVE_MUNICIPIO)
REFERENCES CATALOGOS.TC_MUNICIPIO (CVE_MUNICIPIO);

ALTER TABLE CATALOGOS.TC_COLONIA ADD CONSTRAINT TC_COLONIA_TC_ENT_FED_FK1
FOREIGN KEY (CVE_ENTIDAD_FEDERATIVA)
REFERENCES CATALOGOS.TC_ENTIDAD_FEDERATIVA (CVE_ENTIDAD_FEDERATIVA);


CREATE TABLE CATALOGOS.TC_AREA_CONOCIMIENTO
(
  CVE_AREA_CONOCIMIENTO  BIGSERIAL           NOT NULL PRIMARY KEY ,
  DESCRIPCION            VARCHAR(50)      NOT NULL
);


CREATE TABLE CATALOGOS.TC_BANCO
(
  CVE_BANCO        BIGSERIAL             NOT NULL PRIMARY KEY ,
  NOMBRE_CORTO     VARCHAR(30)            NOT NULL,
  NOMBRE_COMPLETO  VARCHAR(100)           NOT NULL,
  SN_ACTIVO        SMALLINT                       NOT NULL,
  RFC_USUARIO      VARCHAR(13)            NOT NULL,
  FECHA            TIMESTAMP(6)                 NOT NULL
);

CREATE TABLE CATALOGOS.TC_CARRERA
(
  CVE_CARRERA  BIGSERIAL                     NOT NULL PRIMARY KEY,
  DESCRIPCION  VARCHAR(60)                NOT NULL,
  RFC_USUARIO  VARCHAR(13)                NOT NULL,
  FECHA        TIMESTAMP(6)                     NOT NULL
);

CREATE TABLE CATALOGOS.TC_DOCUMENTOS_EXPEDIENTE
(
  CVE_DOCUMENTO  BIGSERIAL              NOT NULL PRIMARY KEY ,
  SECCION        VARCHAR(2)               NOT NULL,
  DOCUMENTO      VARCHAR(40)              NOT NULL,
  REQUERIDO      SMALLINT                   NOT NULL,
  NOMECLATURA    VARCHAR(25)              NOT NULL,
  ID_PARENTEZCO  VARCHAr(100)             DEFAULT NULL
);

CREATE TABLE CATALOGOS.TC_ESTATUS
(
  CVE_ESTATUS       BIGSERIAL                NOT NULL PRIMARY KEY ,
  CVE_TIPO_ESTATUS  BIGINT                NOT NULL,
  DESCRIPCION       VARCHAR(10)           NOT NULL,
  RFC_USUARIO       VARCHAR(13)           NOT NULL,
  FECHA             TIMESTAMP(6)                NOT NULL
);

CREATE TABLE CATALOGOS.TC_MATERIAL_APOYO
(
  ID             BIGSERIAL                         NOT NULL PRIMARY KEY,
  ID_SISTEMA     BIGINT                         NOT NULL,
  RUTA_ABSOLUTA  VARCHAR(250)             NOT NULL,
  NOMBRE         VARCHAR(250)             NOT NULL,
  DESCRIPCION    VARCHAR(250)             NOT NULL,
  FECHA          TIMESTAMP(6),
  EXTENSION      VARCHAR(6),
  TIPO           VARCHAR(10)              NOT NULL
);

CREATE TABLE CATALOGOS.TC_NACIONALIDAD
(
  CVE_NACIONALIDAD  BIGSERIAL                      NOT NULL PRIMARY KEY,
  DESCRIPCION       VARCHAR(50)           NOT NULL,
  RFC_USUARIO       VARCHAR(13)           NOT NULL,
  FECHA             TIMESTAMP(6)                NOT NULL
);

CREATE TABLE CATALOGOS.TC_NIVEL_ACADEMICO
(
  CVE_NIVEL_ACADEMICO  BIGSERIAL                   NOT NULL PRIMARY KEY,
  DESCRIPCION          VARCHAR(50)        NOT NULL,
  APLICA               VARCHAR(1)         NOT NULL
);

CREATE TABLE CATALOGOS.TC_NIVEL_PUESTO
(
  CVE_NIVEL_PUESTO  BIGSERIAL            NOT NULL PRIMARY KEY,
  DESCRIPCION       VARCHAR(100)
);

CREATE TABLE CATALOGOS.TC_PAIS
(
  CVE_PAIS      BIGSERIAL                          NOT NULL PRIMARY KEY,
  ABREVIATURA   VARCHAR(2)                NOT NULL,
  DESCRIPCION   VARCHAR(100)              NOT NULL,
  NACIONALIDAD  VARCHAR(100)              NOT NULL,
  RFC_USUARIO   VARCHAR(13)               NOT NULL,
  FECHA         TIMESTAMP(6)                    NOT NULL
);


